version: '3'
services:
    web:
      container_name: ride_service
      build: .
      restart: unless-stopped
      tty: true
      ports: 
          - 8880:8880
      depends_on:
          - riderequestrabbitmq
 
    riderequestrabbitmq:
      image: rabbitmq:management
      restart: unless-stopped
      tty: true
      ports:
          - "5674:5672"
          - "15674:15672"
    
     
          
         
    
